name: Window 10

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/rustdesk/rustdesk/releases/download/1.2.3-2/rustdesk-1.2.3-2-x86_64.exe -OutFile rustdesk.exe
    - run: .\rustdesk.exe --silent-install 1
    - name: Get RustDesk ID and Password
      run: |
        # Start RustDesk in server mode and set a static password
        Start-Process -FilePath "C:\Program Files\RustDesk\rustdesk.exe" -ArgumentList "-s -p mypassword"
        
        # Wait for RustDesk to start and generate an ID
        Start-Sleep -Seconds 10
        
        # Get the RustDesk ID from the registry
        $rustdeskID = Get-ItemPropertyValue -Path "HKCU:\Software\RustDesk" -Name "myid"
        echo "RustDesk ID: $rustdeskID"
        
        # Print the static password
        echo "RustDesk Password: mypassword"
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@cyb3rking" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
